package model.dao.util;

import exception.DaoOperationException;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class DaoUtil {
    public static Long fetchGeneratedId(PreparedStatement insertStatement) throws SQLException, DaoOperationException {
        // this method allows to retrieve IDs that were generated by the database during insert statement
        ResultSet generatedKeys = insertStatement.getGeneratedKeys();
        if (generatedKeys.next()) { // you need to call next() because cursor is located before the first row
            return generatedKeys.getLong(1);
        } else { // if next() returned false it means that database didn't return any IDs
            throw new DaoOperationException("Can not obtain product ID");
        }
    }
}
